---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cicd-demo-delivery-pipeline
  description: Pipeline for deploying K8s microservice demo
serialPipeline:
  stages:
  - targetId: staging
    profiles:
    - staging
  - targetId: production
    profiles:
    - production
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Staging environment
gke:
  cluster: projects/cicd-pipeline-with-kubernetes/locations/us-central1/clusters/cicd-demo-staging
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production environment
gke:
  cluster: projects/cicd-pipeline-with-kubernetes/locations/us-central1/clusters/cicd-demo-production
