apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: k8s-microservice-demo-pipeline
description: Pipeline for deploying K8s microservice demo
serialPipeline:
  stages:
  - targetId: staging
    profiles: []
    strategy:
      standard:
        verify: {}
  - targetId: production
    profiles: []
    strategy:
      standard:
        verify: {}
