apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: k8s-microservice-demo
requires:
  - configs: [build_frontend]
    path: src/frontend/skaffold.yaml
  - configs: [build_blog]
    path: src/blog/skaffold.yaml
  - configs: [build_auth]
    path: src/auth/skaffold.yaml
deploy:
  kustomize:
    paths:
      - kustomize/base

profiles:
  - name: staging
    build:
      artifacts:
      - image: frontend
      - image: auth
      - image: blog
    deploy:
      kustomize:
        paths:
          - kustomize/staging
  - name: production
    build:
      artifacts:
      - image: frontend
      - image: auth
      - image: blog
    deploy:
      kustomize:
        paths:
          - kustomize/production
