apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: k8s-microservice-demo
requires:
  - configs: [svc_frontend]
    path: src/frontend/skaffold.yaml
  - configs: [svc_blog]
    path: src/blog/skaffold.yaml
  - configs: [svc_auth]
    path: src/auth/skaffold.yaml
deploy:
  kubectl: {}
profiles:
  - name: staging
    manifests:
      kustomize:
        paths:
          - kustomize/staging
  - name: production
    manifests:
      kustomize:
        paths:
          - kustomize/production
