apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: k8s-microservice-demo
build:
  artifacts:
  - image: frontend
    context: src/frontend
    docker:
      dockerfile: Dockerfile
  - image: auth
    context: src/auth
    docker:
      dockerfile: Dockerfile
  - image: blog
    context: src/blog
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - kustomize/base

profiles:
  - name: staging
    build:
      artifacts:
      - image: frontend
      - image: auth
      - image: blog
    deploy:
      kustomize:
        paths:
          - kustomize/staging
  - name: production
    build:
      artifacts:
      - image: frontend
      - image: auth
      - image: blog
    deploy:
      kustomize:
        paths:
          - kustomize/production
