bases:
  - ../base

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ingress
    path: patches/ingress-patch.yaml

patchesStrategicMerge:
  - patches/frontend-deployment-patch.yaml
  - patches/auth-deployment-patch.yaml
  - patches/blog-deployment-patch.yaml
  - patches/domain-config.yaml

images:
  - name: frontend
    newTag: staging
  - name: auth
    newTag: staging
  - name: blog
    newTag: staging