steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pytest

images:
- 'gcr.io/$PROJECT_ID/backend'

artifacts:
  objects:
    location: 'gs://$PROJECT_ID-artifacts/backend'
    paths: ['**']