apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  template:
    spec:
      containers:
      - name: auth
        env:
        - name: ENVIRONMENT
          value: "production"
