apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
spec:
  template:
    spec:
      containers:
      - name: blog
        env:
        - name: ENVIRONMENT
          value: "production"
