steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', '.']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pytest

images:
- 'gcr.io/$PROJECT_ID/frontend'

artifacts:
  objects:
    location: 'gs://$PROJECT_ID-artifacts/frontend'
    paths: ['**']
