apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  # @TODO: need to edit dynamically
  annotations:
    kubernetes.io/ingress.global-static-ip-name: web-ip
spec:
  rules:
  # @TODO: need to edit dynamically
  - host: "demo.electronspark.xyz"
    http:
      paths:
      - path: /api/auth/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /api/blog/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: blog-service
            port:
              number: 80
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 80
