resources:
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - frontend-deployment.yaml
  - auth-deployment.yaml
  - blog-deployment.yaml
  - ingress.yaml
  - domain-config.yaml
images:
  - name: frontend
    newName: frontend
  - name: auth
    newName: auth
  - name: blog
    newName: blog